### PR TITLE
Added json styler

### PR DESCRIPTION
**Pull request by SammyJ**
New to PRs, so hopefully I did this right.

### CODE REVIEW

**Comment by adam8797** [comment]
It looks fine, except you used the wrong Lexer. I believe Scintilla.NET added a JSON Lexer that you’ll probably want to be using here. 

The HTML Lexer is incorrect. 

Thanks,
Adam Schiavone

**Comment by adam8797** [comment]
Sorry, just took another look. 

You’ll want to set the Lexer on line 8, rather than on line 22. 

Thanks,
Adam Schiavone

**Comment by SammyJ** [comment]
Oh, I will correct that asap. I used the html style to strip for a template. I'll update once I get to that.

**Comment by SammyJ** [comment]
Okay, I corrected it as per your request.

**Comment by adam8797** [comment]
Looks good to me. I'll try to release a new NuGet package in the next few days.

**Pull request merged**
